--------------------------------------------------------
--  Constraints for Table XTIPOSAULA
--------------------------------------------------------

  ALTER TABLE "UP201705205"."XTIPOSAULA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."XTIPOSAULA" MODIFY ("ANO_LETIVO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."XTIPOSAULA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."XTIPOSAULA" MODIFY ("CODIGO" NOT NULL ENABLE);
