--------------------------------------------------------
--  Constraints for Table YDOCENTES
--------------------------------------------------------

  ALTER TABLE "UP201705205"."YDOCENTES" MODIFY ("NR" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDOCENTES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDOCENTES" MODIFY ("SIGLA" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDOCENTES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDOCENTES" ADD CONSTRAINT "YDOCENTES_PKEY" PRIMARY KEY ("NR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
