--------------------------------------------------------
--  DDL for Table YDOCENTES
--------------------------------------------------------

  CREATE TABLE "UP201705205"."YDOCENTES" 
   (	"NR" NUMBER, 
	"NOME" VARCHAR2(75 BYTE), 
	"SIGLA" VARCHAR2(8 BYTE), 
	"CATEGORIA" NUMBER, 
	"PROPRIO" VARCHAR2(25 BYTE), 
	"APELIDO" VARCHAR2(25 BYTE), 
	"ESTADO" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
