--------------------------------------------------------
--  Constraints for Table YDSD
--------------------------------------------------------

  ALTER TABLE "UP201705205"."YDSD" MODIFY ("NR" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDSD" MODIFY ("HORAS" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YDSD" ADD CONSTRAINT "YDSD_PKEY" PRIMARY KEY ("NR", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
