--------------------------------------------------------
--  DDL for Table YDSD
--------------------------------------------------------

  CREATE TABLE "UP201705205"."YDSD" 
   (	"NR" NUMBER(*,0), 
	"ID" NUMBER(10,0), 
	"HORAS" NUMBER(4,2), 
	"FATOR" NUMBER(3,2), 
	"ORDEM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
