--------------------------------------------------------
--  DDL for Table YOCORRENCIAS
--------------------------------------------------------

  CREATE TABLE "UP201705205"."YOCORRENCIAS" 
   (	"CODIGO" VARCHAR2(9 BYTE), 
	"ANO_LETIVO" VARCHAR2(9 BYTE), 
	"PERIODO" VARCHAR2(2 BYTE), 
	"INSCRITOS" NUMBER(*,0), 
	"COM_FREQUENCIA" NUMBER(*,0), 
	"APROVADOS" NUMBER(*,0), 
	"OBJETIVOS" VARCHAR2(4000 BYTE), 
	"CONTEUDO" VARCHAR2(4000 BYTE), 
	"DEPARTAMENTO" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
