--------------------------------------------------------
--  Constraints for Table YOCORRENCIAS
--------------------------------------------------------

  ALTER TABLE "UP201705205"."YOCORRENCIAS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YOCORRENCIAS" MODIFY ("ANO_LETIVO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YOCORRENCIAS" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YOCORRENCIAS" ADD CONSTRAINT "YOCORRENCIAS_PKEY" PRIMARY KEY ("CODIGO", "ANO_LETIVO", "PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
