--------------------------------------------------------
--  Constraints for Table YTIPOSAULA
--------------------------------------------------------

  ALTER TABLE "UP201705205"."YTIPOSAULA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YTIPOSAULA" MODIFY ("ANO_LETIVO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YTIPOSAULA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YTIPOSAULA" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YTIPOSAULA" ADD CONSTRAINT "YTIPOAULA_PKEY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
