--------------------------------------------------------
--  DDL for Table YTIPOSAULA
--------------------------------------------------------

  CREATE TABLE "UP201705205"."YTIPOSAULA" 
   (	"ID" NUMBER(10,0), 
	"TIPO" VARCHAR2(2 BYTE), 
	"ANO_LETIVO" VARCHAR2(9 BYTE), 
	"PERIODO" VARCHAR2(2 BYTE), 
	"CODIGO" VARCHAR2(9 BYTE), 
	"TURNOS" NUMBER(4,2), 
	"N_AULAS" NUMBER, 
	"HORAS_TURNO" NUMBER(4,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
