--------------------------------------------------------
--  Constraints for Table YUCS
--------------------------------------------------------

  ALTER TABLE "UP201705205"."YUCS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YUCS" MODIFY ("DESIGNACAO" NOT NULL ENABLE);
  ALTER TABLE "UP201705205"."YUCS" ADD CONSTRAINT "YUCS_PKEY" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
