--------------------------------------------------------
--  DDL for Table YUCS
--------------------------------------------------------

  CREATE TABLE "UP201705205"."YUCS" 
   (	"CODIGO" VARCHAR2(9 BYTE), 
	"DESIGNACAO" VARCHAR2(150 BYTE), 
	"SIGLA_UC" VARCHAR2(6 BYTE), 
	"CURSO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
